/**
 * GENERATED by tools/cn-font-catalog/build.mjs — 请勿手改，重跑管线更新。
 * 构建日期：2026-08-30 | 目录规模：83 包探针 → 105 族收录 / 9 条排除
 *
 * T42 S1：中文网字计划全量目录（registry 精选 6 族之外的 @chinese-fonts/* 包）。
 * catalog 族白名单语义 = 默认停用（opt-in，D-c）；授权以包内 license 原文为准，未审计（D-d）。
 */

export interface CnFontCatalogEntry {
  family: string
  package: string
  /** 构建时实解版本（钉扎可重现 + piece 缓存键稳定，D-g） */
  version: string
  /** npm 包内 license 字段原文（未审计，展示用） */
  license: string
  variable: boolean
  /** result.css 实见字重（静态档集合；VF 为区间端点） */
  weights: number[]
  /** 非 ASCII 目录名包的回退 CDN base（缺省 = jsdelivr）；运行时透传 descriptor.baseURL */
  base?: string
}

export const CN_FONT_CATALOG: CnFontCatalogEntry[] = [
  {
    family: '极影毁片文宋 Medium',
    package: '@chinese-fonts/jyhpws',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [500],
    base: 'https://unpkg.com'
  },
  {
    family: '荆南俊俊体',
    package: '@chinese-fonts/jnjj',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [700]
  },
  {
    family: '快看世界体',
    package: '@chinese-fonts/kksjt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: '平方赖江湖飞扬体',
    package: '@chinese-fonts/pfljhfyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: '平方赖江湖琅琊体',
    package: '@chinese-fonts/pfljhlyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: '瑞美加张清平硬笔行书',
    package: '@chinese-fonts/rmjzqpybxs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: '峄山碑篆体',
    package: '@chinese-fonts/ysbzt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'bailubangbangshouxieti',
    package: '@chinese-fonts/blbbsxt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'BWCKKT',
    package: '@chinese-fonts/bwckkt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [300, 400, 700],
    base: 'https://unpkg.com'
  },
  {
    family: 'CEF Fonts CJK',
    package: '@chinese-fonts/cef',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'CEF Fonts CJK Mono',
    package: '@chinese-fonts/cef',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'chengrongguangke',
    package: '@chinese-fonts/crgkk',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Child Fun Sans Demo',
    package: '@chinese-fonts/yqt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Cubic 11',
    package: '@chinese-fonts/cubic',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Douyin Sans',
    package: '@chinese-fonts/dymh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [700]
  },
  {
    family: 'DOUYU Font',
    package: '@chinese-fonts/dyzgt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'FlyFlowerSong',
    package: '@chinese-fonts/fhst',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'FontQu Smile 常规',
    package: '@chinese-fonts/zzqxmxht',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'GuanKiapTsingKhai',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-S',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-S-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-T',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-T-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-TW',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-TW-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-W',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'GuanKiapTsingKhai-W-90',
    package: '@chinese-fonts/guan-kiap-tsing-khai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Hangeuljaemin4.0',
    package: '@chinese-fonts/hqzmt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'hongleixingshu',
    package: '@chinese-fonts/hlxsjt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'huangyinqi zhaopai',
    package: '@chinese-fonts/hyqzp',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Huiwen-mincho',
    package: '@chinese-fonts/hwmct',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'I.Ngaan',
    package: '@chinese-fonts/yidianyan',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'jiangxizhuokai',
    package: '@chinese-fonts/jxzk',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'LogoSC LongZhuTi',
    package: '@chinese-fonts/bxzlzt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Long Cang',
    package: '@chinese-fonts/yzklct',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'LXGW Bright',
    package: '@chinese-fonts/lxgwwenkaibright',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW Bright Light',
    package: '@chinese-fonts/lxgwwenkaibright',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'LXGW Bright Medium',
    package: '@chinese-fonts/lxgwwenkaibright',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [500]
  },
  {
    family: 'LXGW Marker Gothic',
    package: '@chinese-fonts/lxgwmanhei',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW Neo ZhiSong',
    package: '@chinese-fonts/lxgw-neo-zhi-song',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW WenKai Mono Screen',
    package: '@chinese-fonts/lywkpmydb',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'LXGW WenKai Screen',
    package: '@chinese-fonts/lywkpmydb',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'MaoKenTangYuan (beta)',
    package: '@chinese-fonts/mkwtyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'MaokenZhuyuanTi',
    package: '@chinese-fonts/mkzyt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Maple Mono CN',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400, 700]
  },
  {
    family: 'Maple Mono CN ExtraBold',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [800]
  },
  {
    family: 'Maple Mono CN ExtraLight',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [200]
  },
  {
    family: 'Maple Mono CN Light',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'Maple Mono CN Medium',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [500]
  },
  {
    family: 'Maple Mono CN SemiBold',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [600]
  },
  {
    family: 'Maple Mono CN Thin',
    package: '@chinese-fonts/maple-mono-cn',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [100]
  },
  {
    family: 'Moon Stars Kai',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400, 700]
  },
  {
    family: 'Moon Stars Kai HW',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400, 700]
  },
  {
    family: 'Moon Stars Kai HW Light',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'Moon Stars Kai Light',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'Moon Stars Kai T',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400, 700]
  },
  {
    family: 'Moon Stars Kai T HW',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400, 700]
  },
  {
    family: 'Moon Stars Kai T HW Light',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'Moon Stars Kai T Light',
    package: '@chinese-fonts/moon-stars-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'MuzaiPixel',
    package: '@chinese-fonts/mzxst',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'nzgrKangxi',
    package: '@chinese-fonts/rzjkxzdmh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'nzgrRuYinZouZhangKai',
    package: '@chinese-fonts/rzjryzzk',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'PangMenZhengDao-XiXian',
    package: '@chinese-fonts/pmzdxxt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'PING FANG GONG ZI TI',
    package: '@chinese-fonts/pfgzt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'PING FANG MENG MNEG DA',
    package: '@chinese-fonts/pfmmd',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'qiantubifengshouxieti',
    package: '@chinese-fonts/qtbfsxt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'QIJIFALLBACK',
    package: '@chinese-fonts/hldqjt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'QuanPixel 8px',
    package: '@chinese-fonts/qxs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'shetumodengxiaofangti',
    package: '@chinese-fonts/stmdxf',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Slidefu',
    package: '@chinese-fonts/ysfxt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Smiley Sans Oblique',
    package: '@chinese-fonts/dyh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'SoukouMincho',
    package: '@chinese-fonts/zjmc',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Source Han Serif CN for Display',
    package: '@chinese-fonts/sypxzs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'STDongGuanTi',
    package: '@chinese-fonts/stdgt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'STDongGuanTi Bld',
    package: '@chinese-fonts/stdgt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [700],
    base: 'https://unpkg.com'
  },
  {
    family: 'STDongGuanTi Light',
    package: '@chinese-fonts/stdgt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300],
    base: 'https://unpkg.com'
  },
  {
    family: 'SuCaiJiShi-SheHuiTi',
    package: '@chinese-fonts/scjssh',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'The Peak Font 隨峰體 Beta',
    package: '@chinese-fonts/sft',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'ToneOZ-Pinyin-Kai-Simplified',
    package: '@chinese-fonts/toneoz-pinyin-kai-simplified',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Pinyin-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Pinyin-WenKai-Light',
    package: '@chinese-fonts/toneoz-pinyin-wenkai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'ToneOZ-Pinyin-WenKai-Medium',
    package: '@chinese-fonts/toneoz-pinyin-wenkai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [500]
  },
  {
    family: 'ToneOZ-Pinyin-WenKai-Regular',
    package: '@chinese-fonts/toneoz-pinyin-wenkai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-PinyinW-Kai-Simplified',
    package: '@chinese-fonts/toneoz-pinyin-kai-simplified',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-RadicalZ-KaiTraditional',
    package: '@chinese-fonts/toneoz-radicalz-kai',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-YinPZ-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'ToneOZ-Zhuyin-Tsuipita-TC',
    package: '@chinese-fonts/toneoz-tsuipita',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'TsangerZhoukeZhengdabangshu',
    package: '@chinese-fonts/cezkzdbs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Xiaohe Simplify Sans VF',
    package: '@chinese-fonts/xiaohe-simplify',
    version: '2.0.0',
    license: 'MIT',
    variable: true,
    weights: [250, 900]
  },
  {
    family: 'Xiaohe Simplify Serif VF',
    package: '@chinese-fonts/xiaohe-simplify',
    version: '2.0.0',
    license: 'MIT',
    variable: true,
    weights: [250, 900]
  },
  {
    family: 'xiaowei',
    package: '@chinese-fonts/zkxw',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'XuandongKaishu',
    package: '@chinese-fonts/xuandongkaishu',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'YEFONTXiaoShiTou',
    package: '@chinese-fonts/yzgcxst',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'YouSheBiaoTiHei',
    package: '@chinese-fonts/ysbth',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'YouSheShaYuFeiTeJianKangTi',
    package: '@chinese-fonts/syftjkt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'YuFanXinYu',
    package: '@chinese-fonts/yfxy',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400, 700]
  },
  {
    family: 'YuFanXinYu-Light',
    package: '@chinese-fonts/yfxy',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [300]
  },
  {
    family: 'YuFanXinYu-Medium',
    package: '@chinese-fonts/yfxy',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [500]
  },
  {
    family: 'YunFengchongqingbangbangti',
    package: '@chinese-fonts/cqscbbt',
    version: '2.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'Zhi Mang Xing',
    package: '@chinese-fonts/zqzmxs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'Zhuque Fangsong (technical preview)',
    package: '@chinese-fonts/zqfs',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400]
  },
  {
    family: 'zihunbiantaoti',
    package: '@chinese-fonts/zhbtt',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  },
  {
    family: 'ZoomlaMengyas-A080',
    package: '@chinese-fonts/zlmyz',
    version: '3.0.0',
    license: 'MIT',
    variable: false,
    weights: [400],
    base: 'https://unpkg.com'
  }
]

const catalogByFamily = new Map(CN_FONT_CATALOG.map((entry) => [entry.family, entry]))

export function cnCatalogEntry(family: string): CnFontCatalogEntry | undefined {
  return catalogByFamily.get(family)
}

export function isCnCatalogFamily(family: string): boolean {
  return catalogByFamily.has(family)
}
