name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x64

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: desktop/src-tauri -> target
          key: ${{ matrix.target }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.10

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        with:
          tauriScript: bunx tauri
          args: --target ${{ matrix.target }}
          releaseDraft: true